baseURL = "http://example.org/"
languageCode = "en-us"
title = "Cultura Mapache!"
theme = ["showcase"]
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
timeout = 60000 

[params]
  author = "Maestra Kirk, Kyle Kirk, Roberto Pacheco"
  title = "Cultura Mapache!"
  description = "Minimal, one page, theme for showcasing your work"
  message = ""
  hideAutoMenu = false
  heroimg = "imgs/clip-art-banner-7.png"

[menu]

    [[menu.main]]
        name = "Rosedale"
        url = "http://rosedale.chicousd.org/"

    [[menu.main]]
        name = "Testing"
        url = "/gallery/gallery/"


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false