baseURL = "https://www.culturamapache.com/"
languageCode = "en-us"
title = "Cultura Mapache"
theme = ["hugo-theme-bootie-docs"]
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
timeout = 60000 

[params]
  author = "Krizia Garcia, Kelly Kirk, Kyle Kirk, Roberto Pacheco"
  title = "Cultura Mapache!"
  description = "Welcome."
  message = ""
  hideAutoMenu = false
  logo = "static/imgs/Rosedale_logo.png"

[menu]

    [[menu.main]]
        name = "Info"
        url = "/info/info/"

    [[menu.main]]
        name = "Galería"
        url = "/galeria/galeria/"

    [[menu.main]]
        name = "Proyectos"
        url = "/proyectos/proyectos/"

    [[menu.main]]
        name = "Cosas Extras"
        url = "/cosas/cosas/"
    


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false