baseURL = "https://culturamapache.com/"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en-us"
publishDir = "public"
theme = ["SimpleIntro", "hugo-shortcode-gallery"]
title = "Rosedales Cultura Mapache Site!"
[[menu.main]]
identifier = "Pictures!"
name = "Pictures"
weight = 2
[menus]
[params]
mainText = "A placeholder for things."
mainTitle = "Pacos Paradise"
mainbg = "resources/_gen/images/background.jpg"
