baseURL = "https://www.culturamapache.com/"
languageCode = "en-us"
title = "Cultura Mapache!"
theme = ["hugo-theme-bootie-docs"]
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
timeout = 60000 

[params]
  author = "Maestra Kirk, Kyle Kirk, Roberto Pacheco"
  title = "Cultura Mapache!"
  description = "Welcome."
  message = ""
  hideAutoMenu = false

[menu]

    [[menu.main]]
        name = "Rosedale"
        url = "http://rosedale.chicousd.org/"

    [[menu.main]]
        name = "Altar"
        url = "/gallery/gallery/"


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false