baseURL = "https://culturamapache.com/"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en-us"
publishDir = "public"
[params]
    mainbg = "static/background.jpg"
    mainTitle = "Pacos Paradise"
    mainText = "A placeholder for things."

theme = ["SimpleIntro", "hugo-shortcode-gallery"]
title = "Rosedales Cultura Mapache Site!"
[[menu.main]]
name = "Biblioteca"
url = "http://rosedale.chicousd.org/LibraryBiblioteca/index.html"
weight = 3
[[menu.main]]
identifier = "Pictures!"
name = "Pictures"
weight = 1
[menus]
