baseURL = "https://culturamapache.com/"
languageCode = "en-us"
title = "Rosedales Cultura Mapache Site!"
theme = ["SimpleIntro", "hugo-shortcode-gallery"]
publishDir = "public"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    mainbg = "resources/_gen/images/background.jpg"
    mainTitle = "Pacos Paradise"
    mainText = "A placeholder for things."

[menus]
    [[menu.main]]
        identifier = "Pictures!"
        name = "Pictures"
        url = ""
    [[menu.main]]
        identifier = "Other!"
        name = "Other"
        url = ""