---
label: default
hide_body: true
fields:
- name: donkey_kong
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Donkey kong
  description: King of the Donkeys
pages:
- content/test.md
